export const categories = [
	{ id: 1, name: "Beer" },
	{ id: 2, name: "Cocktail" },
	{ id: 3, name: "Cocoa" },
	{ id: 4, name: "Coffee / Tea" },
	{ id: 5, name: "Homemade Liqueur" },
	{ id: 6, name: "Ordinary Drink" },
	{ id: 7, name: "Other / Unknown" },
	{ id: 8, name: "Punch / Party Drink" },
	{ id: 9, name: "Shake" },
	{ id: 10, name: "Shot" },
	{ id: 11, name: "Soft Drink" },
];

export const glasses = [
	{ id: 1, name: "Balloon Glass" },
	{ id: 2, name: "Beer Glass" },
	{ id: 3, name: "Beer mug" },
	{ id: 4, name: "Beer pilsner" },
	{ id: 5, name: "Brandy snifter" },
	{ id: 6, name: "Champagne flute" },
	{ id: 7, name: "Cocktail glass" },
	{ id: 8, name: "Coffee mug" },
	{ id: 9, name: "Collins glass" },
	{ id: 10, name: "Copper Mug" },
	{ id: 11, name: "Cordial glass" },
	{ id: 12, name: "Coupe Glass" },
	{ id: 13, name: "Highball glass" },
	{ id: 14, name: "Hurricane glass" },
	{ id: 15, name: "Irish coffee cup" },
	{ id: 16, name: "Jar" },
	{ id: 17, name: "Margarita glass" },
	{ id: 18, name: "Margarita/Coupette glass" },
	{ id: 19, name: "Martini Glass" },
	{ id: 20, name: "Mason jar" },
	{ id: 21, name: "Nick and Nora Glass" },
	{ id: 22, name: "Old-fashioned glass" },
	{ id: 23, name: "Parfait glass" },
	{ id: 24, name: "Pint glass" },
	{ id: 25, name: "Pitcher" },
	{ id: 26, name: "Pousse cafe glass" },
	{ id: 27, name: "Punch bowl" },
	{ id: 28, name: "Shot glass" },
	{ id: 29, name: "Whiskey Glass" },
	{ id: 30, name: "Whiskey sour glass" },
	{ id: 31, name: "White wine glass" },
	{ id: 32, name: "Wine Glass" },
];

export const types = [
	{ id: 1, name: "Alcoholic" },
	{ id: 2, name: "Non alcoholic" },
	{ id: 3, name: "Optional alcohol" },
];
